// Existing auth types - keep these
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// Add profile and user type actions
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING';

// Verification actions
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';
export const VERIFY_PHONE_REQUEST = 'VERIFY_PHONE_REQUEST';
export const VERIFY_PHONE_SUCCESS = 'VERIFY_PHONE_SUCCESS';
export const VERIFY_PHONE_FAILURE = 'VERIFY_PHONE_FAILURE';
export const VERIFY_ID_REQUEST = 'VERIFY_ID_REQUEST';
export const VERIFY_ID_SUCCESS = 'VERIFY_ID_SUCCESS';
export const VERIFY_ID_FAILURE = 'VERIFY_ID_FAILURE';
export const GET_VERIFICATION_STATUS_REQUEST = 'GET_VERIFICATION_STATUS_REQUEST';
export const GET_VERIFICATION_STATUS_SUCCESS = 'GET_VERIFICATION_STATUS_SUCCESS';
export const GET_VERIFICATION_STATUS_FAILURE = 'GET_VERIFICATION_STATUS_FAILURE';

// Companionship actions
export const GET_COMPANIONS_REQUEST = 'GET_COMPANIONS_REQUEST';
export const GET_COMPANIONS_SUCCESS = 'GET_COMPANIONS_SUCCESS';
export const GET_COMPANIONS_FAILURE = 'GET_COMPANIONS_FAILURE';
export const REQUEST_COMPANIONSHIP_REQUEST = 'REQUEST_COMPANIONSHIP_REQUEST';
export const REQUEST_COMPANIONSHIP_SUCCESS = 'REQUEST_COMPANIONSHIP_SUCCESS';
export const REQUEST_COMPANIONSHIP_FAILURE = 'REQUEST_COMPANIONSHIP_FAILURE';

// Safety actions
export const REPORT_USER_REQUEST = 'REPORT_USER_REQUEST';
export const REPORT_USER_SUCCESS = 'REPORT_USER_SUCCESS';
export const REPORT_USER_FAILURE = 'REPORT_USER_FAILURE';
export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE';
export const SHARE_LOCATION_REQUEST = 'SHARE_LOCATION_REQUEST';
export const SHARE_LOCATION_SUCCESS = 'SHARE_LOCATION_SUCCESS';
export const SHARE_LOCATION_FAILURE = 'SHARE_LOCATION_FAILURE';

// New Auth actions
export const SET_AUTH_STATE = 'SET_AUTH_STATE';

// New Profile actions
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

// New Safety actions
export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAILURE = 'UNBLOCK_USER_FAILURE';
export const FETCH_SAFETY_SETTINGS_REQUEST = 'FETCH_SAFETY_SETTINGS_REQUEST';
export const FETCH_SAFETY_SETTINGS_SUCCESS = 'FETCH_SAFETY_SETTINGS_SUCCESS';
export const FETCH_SAFETY_SETTINGS_FAILURE = 'FETCH_SAFETY_SETTINGS_FAILURE';
export const UPDATE_SAFETY_SETTINGS_REQUEST = 'UPDATE_SAFETY_SETTINGS_REQUEST';
export const UPDATE_SAFETY_SETTINGS_SUCCESS = 'UPDATE_SAFETY_SETTINGS_SUCCESS';
export const UPDATE_SAFETY_SETTINGS_FAILURE = 'UPDATE_SAFETY_SETTINGS_FAILURE';
export const FETCH_BLOCKED_USERS_REQUEST = 'FETCH_BLOCKED_USERS_REQUEST';
export const FETCH_BLOCKED_USERS_SUCCESS = 'FETCH_BLOCKED_USERS_SUCCESS';
export const FETCH_BLOCKED_USERS_FAILURE = 'FETCH_BLOCKED_USERS_FAILURE';

// New Verification actions (from verificationActions.ts)
export const REQUEST_EMAIL_CODE_REQUEST = 'REQUEST_EMAIL_CODE_REQUEST';
export const REQUEST_EMAIL_CODE_SUCCESS = 'REQUEST_EMAIL_CODE_SUCCESS';
export const REQUEST_EMAIL_CODE_FAILURE = 'REQUEST_EMAIL_CODE_FAILURE';
export const REQUEST_PHONE_CODE_REQUEST = 'REQUEST_PHONE_CODE_REQUEST';
export const REQUEST_PHONE_CODE_SUCCESS = 'REQUEST_PHONE_CODE_SUCCESS';
export const REQUEST_PHONE_CODE_FAILURE = 'REQUEST_PHONE_CODE_FAILURE';
export const SUBMIT_PHOTO_REQUEST = 'SUBMIT_PHOTO_REQUEST';
export const SUBMIT_PHOTO_SUCCESS = 'SUBMIT_PHOTO_SUCCESS';
export const SUBMIT_PHOTO_FAILURE = 'SUBMIT_PHOTO_FAILURE';

// Message actions (from messageReducer context, ensure these have corresponding action creators)
export const FETCH_CONVERSATIONS_REQUEST = 'FETCH_CONVERSATIONS_REQUEST';
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_FAILURE = 'FETCH_CONVERSATIONS_FAILURE';
export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
export const MARK_MESSAGES_AS_READ_REQUEST = 'MARK_MESSAGES_AS_READ_REQUEST';
export const MARK_MESSAGES_AS_READ_SUCCESS = 'MARK_MESSAGES_AS_READ_SUCCESS';
export const MARK_MESSAGES_AS_READ_FAILURE = 'MARK_MESSAGES_AS_READ_FAILURE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'; // For WebSocket/real-time updates
export const SET_ACTIVE_CONVERSATION = 'SET_ACTIVE_CONVERSATION'; // UI state for active chat

// Match actions (from matchReducer context, ensure these have corresponding action creators)
export const FETCH_POTENTIAL_MATCHES_REQUEST = 'FETCH_POTENTIAL_MATCHES_REQUEST';
export const FETCH_POTENTIAL_MATCHES_SUCCESS = 'FETCH_POTENTIAL_MATCHES_SUCCESS';
export const FETCH_POTENTIAL_MATCHES_FAILURE = 'FETCH_POTENTIAL_MATCHES_FAILURE';
export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';
export const FETCH_MATCHES_REQUEST = 'FETCH_MATCHES_REQUEST';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAILURE = 'FETCH_MATCHES_FAILURE';
export const CREATE_MATCH_REQUEST = 'CREATE_MATCH_REQUEST';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_FAILURE = 'CREATE_MATCH_FAILURE';
export const RESPOND_TO_MATCH_REQUEST = 'RESPOND_TO_MATCH_REQUEST';
export const RESPOND_TO_MATCH_SUCCESS = 'RESPOND_TO_MATCH_SUCCESS';
export const RESPOND_TO_MATCH_FAILURE = 'RESPOND_TO_MATCH_FAILURE';

// Engagement actions (from BadgesScreen context, assuming these would be in engagementActions.ts)
export const FETCH_BADGES_REQUEST = 'FETCH_BADGES_REQUEST';
export const FETCH_BADGES_SUCCESS = 'FETCH_BADGES_SUCCESS';
export const FETCH_BADGES_FAILURE = 'FETCH_BADGES_FAILURE';
export const FETCH_ACHIEVEMENTS_REQUEST = 'FETCH_ACHIEVEMENTS_REQUEST';
export const FETCH_ACHIEVEMENTS_SUCCESS = 'FETCH_ACHIEVEMENTS_SUCCESS';
export const FETCH_ACHIEVEMENTS_FAILURE = 'FETCH_ACHIEVEMENTS_FAILURE';

// Monetization actions (from SubscriptionScreen context, assuming these would be in monetizationActions.ts)
export const FETCH_SUBSCRIPTION_PLANS_REQUEST = 'FETCH_SUBSCRIPTION_PLANS_REQUEST';
export const FETCH_SUBSCRIPTION_PLANS_SUCCESS = 'FETCH_SUBSCRIPTION_PLANS_SUCCESS';
export const FETCH_SUBSCRIPTION_PLANS_FAILURE = 'FETCH_SUBSCRIPTION_PLANS_FAILURE';
export const FETCH_USER_SUBSCRIPTION_REQUEST = 'FETCH_USER_SUBSCRIPTION_REQUEST';
export const FETCH_USER_SUBSCRIPTION_SUCCESS = 'FETCH_USER_SUBSCRIPTION_SUCCESS';
export const FETCH_USER_SUBSCRIPTION_FAILURE = 'FETCH_USER_SUBSCRIPTION_FAILURE';
export const CREATE_CHECKOUT_SESSION_REQUEST = 'CREATE_CHECKOUT_SESSION_REQUEST';
export const CREATE_CHECKOUT_SESSION_SUCCESS = 'CREATE_CHECKOUT_SESSION_SUCCESS';
export const CREATE_CHECKOUT_SESSION_FAILURE = 'CREATE_CHECKOUT_SESSION_FAILURE';
export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = 'CANCEL_SUBSCRIPTION_FAILURE';
