require_relative '../node_modules/react-native/scripts/react_native_pods'
$RNVersion = '0.78.0' # Added this line

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Force the use of frameworks instead of static libraries for all pods
use_frameworks! :linkage => :static

target 'GetMeBuddyApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default
    :hermes_enabled => flags[:hermes_enabled],
    # Remove the Flipper configuration entirely - we're using frameworks which are incompatible with Flipper
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # Ensure all pods support the same deployment target as your app
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Fix for Xcode 15
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        
        # Fix React warnings
        if target.name == 'React-Core' || target.name.include?('React-')
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end

        # Fix warnings that cause build failures
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'NO'
      end
    end
    
    react_native_post_install(installer)
  end
end